"""
API endpoint for estimate_and_track_from_messages
Generated by Advanced Feature Stub Generator
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, validator
from typing import Optional, Dict, Any, List
from datetime import datetime
from threading import Lock

router = APIRouter()


# -------------------------------
# In-memory tracking state
# -------------------------------
_tracking_store: Dict[str, float] = {}
_tracking_lock: Lock = Lock()

# Supported models with cost-per-1k-tokens (USD)
_MODEL_PRICING: Dict[str, float] = {
    "gpt-3.5-turbo": 0.002,
    "gpt-4": 0.06,
    "gpt-4-32k": 0.12,
}


# -------------------------------
# Utility helpers
# -------------------------------
def _approximate_token_count(text: str) -> int:
    """
    Very rough heuristic for estimating token count.
    Splits text by whitespace and punctuation replacements,
    then applies a multiplier to account for average token/word ratio.
    """
    if not text:
        return 0
    # Split on whitespace
    words = text.split()
    # Heuristic: average OpenAI token ≈ 0.75 English words -> tokens ~ words / 0.75
    # To avoid floating rounding issues, multiply by 4 // 3
    token_estimate = int(len(words) / 0.75)
    return max(token_estimate, 1)


def _estimate_message_tokens(messages: List[Dict[str, str]]) -> int:
    """
    Estimate total tokens for a list of chat messages.
    Each message is expected to contain a 'content' field.
    """
    total_tokens = 0
    for msg in messages:
        content = msg.get("content", "")
        total_tokens += _approximate_token_count(content)
    # Add minimal overhead per message (role & delimiters)
    total_tokens += 4 * len(messages)
    return total_tokens


# -------------------------------
# Request / Response Models
# -------------------------------
class MessageModel(BaseModel):
    role: str = Field(..., description="Role of the sender (e.g., system, user, assistant)")
    content: str = Field(..., description="Content of the message")
    name: Optional[str] = Field(None, description="Optional name of the sender")

    @validator("role")
    def validate_role(cls, v: str) -> str:
        allowed = {"system", "user", "assistant", "tool"}
        if v not in allowed:
            raise ValueError(f"Invalid role '{v}'. Allowed roles: {allowed}")
        return v


class estimate_and_track_from_messagesRequest(BaseModel):
    """
    Request model for estimate_and_track_from_messages.
    """
    model: str = Field(..., description="LLM model name used for estimation")
    messages: List[MessageModel] = Field(..., description="List of messages forming the prompt")
    track: bool = Field(False, description="Whether to persist cost under tracking_id")
    tracking_id: Optional[str] = Field(
        None,
        description="An identifier used to accumulate and retrieve tracked cost"
    )

    @validator("model")
    def validate_model(cls, v: str) -> str:
        if v not in _MODEL_PRICING:
            raise ValueError(f"Unsupported model '{v}'. Supported models: {list(_MODEL_PRICING.keys())}")
        return v

    @validator("tracking_id")
    def validate_tracking_id(cls, v: Optional[str], values: Dict[str, Any]) -> Optional[str]:
        if values.get("track") and not v:
            raise ValueError("tracking_id is required when track is True")
        return v


class estimate_and_track_from_messagesResponse(BaseModel):
    """
    Response model for estimate_and_track_from_messages.
    """
    success: bool
    message: str
    data: Optional[Dict[str, Any]] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# -------------------------------
# Endpoint Implementation
# -------------------------------
@router.post("/api/v1/estimate-and-track-from-messages", response_model=estimate_and_track_from_messagesResponse)
async def estimate_and_track_from_messages_endpoint(
    request: estimate_and_track_from_messagesRequest,
) -> estimate_and_track_from_messagesResponse:
    """
    Estimate the token usage and cost for a list of chat messages, and optionally
    aggregate the cost under a tracking identifier.

    Steps:
    1. Estimate total tokens for the provided messages using a simple heuristic.
    2. Calculate the cost based on model pricing.
    3. If tracking is requested, update the in-memory store and include the running
       total in the response.
    """
    try:
        # Estimate token count
        total_tokens = _estimate_message_tokens([msg.dict() for msg in request.messages])

        # Calculate cost
        price_per_1k = _MODEL_PRICING[request.model]
        estimated_cost = round((total_tokens / 1000) * price_per_1k, 6)

        response_data: Dict[str, Any] = {
            "model": request.model,
            "estimated_tokens": total_tokens,
            "estimated_cost_usd": estimated_cost,
        }

        # Handle cost tracking
        if request.track and request.tracking_id:
            with _tracking_lock:
                previous_total = _tracking_store.get(request.tracking_id, 0.0)
                new_total = round(previous_total + estimated_cost, 6)
                _tracking_store[request.tracking_id] = new_total
            response_data["tracking_id"] = request.tracking_id
            response_data["total_tracked_cost_usd"] = new_total

        return estimate_and_track_from_messagesResponse(
            success=True,
            message="Estimation completed successfully.",
            data=response_data,
        )

    except HTTPException:
        # Re-raise FastAPI HTTPExceptions unchanged
        raise
    except ValueError as ve:
        # Validation error that passed pydantic but failed custom logic
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        # Unhandled error
        raise HTTPException(
            status_code=500,
            detail=f"estimate_and_track_from_messages execution failed: {str(e)}"
        ) from e


# Export router for main application
__all__ = [
    "router",
    "estimate_and_track_from_messagesRequest",
    "estimate_and_track_from_messagesResponse",
]