# DISABLED: Manual trigger only to reduce noise
name: Autonomy Planning (Disabled)
on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This workflow is disabled to reduce email noise'
