name: Documentation Alignment

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs-alignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run docs alignment check
        run: |
          python scripts/check_docs_alignment.py --strict

