# Weekly scan disabled - use manual trigger to reduce noise
name: Weekly Scan (Manual)
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo 'Run manually when needed'
